repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.6
  hooks:
    - id: ruff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.0
  hooks:
    - id: mypy
      additional_dependencies:
        - types-PyYaml
        - types-requests
        - types-tqdm
      args: ['--no-strict-optional', '--ignore-missing-imports']
      exclude: ^tests/
